// Categorías de referencia usadas por la comunidad de péptidos. Un péptido puede
// pertenecer a más de una (ej. BPC-157 es recuperación Y salud digestiva).
// Las etiquetas visibles viven en messages/*.json bajo "PeptideCategories", con
// una clave por cada id de aquí abajo.
export const PEPTIDE_CATEGORY_IDS = [
  "peso",
  "musculo_gh",
  "recuperacion",
  "longevidad",
  "sueno",
  "piel_belleza",
  "cognicion",
  "libido",
  "intestinal",
  "inmunidad",
] as const;

export type PeptideCategoryId = (typeof PEPTIDE_CATEGORY_IDS)[number];

// Nivel de confianza del dato de vida media (halfLife): "alto" cuando viene de
// ficha técnica FDA o un estudio farmacocinético publicado en humanos; "medio"
// cuando la literatura secundaria es consistente pero sin PK humana formal;
// "bajo" cuando solo hay estudios preclínicos (animal) o estimaciones dispares;
// "sin-dato" cuando no existe ningún valor confiable — nunca se inventa un número.
export type HalfLifeConfidence = "alto" | "medio" | "bajo" | "sin-dato";

export type PeptideProfile = {
  name: string;
  route: string;
  commonDose: string;
  doseUnit: string;
  vialAmount: string;
  vialUnit: string;
  bacWater: string;
  frequency: string;
  categories: PeptideCategoryId[];
  tags: string[];
  description: string;
  halfLife: string;
  halfLifeConfidence: HalfLifeConfidence;
  // Los 5 campos de abajo son contenido editorial de la Biblioteca (no del
  // formulario de dosis). Nunca se inventa un dato concreto: si no hay
  // evidencia confiable se dice explícitamente en evidenceLevel.
  howItWorks: string;
  mostReported: string[];
  evidenceLevel: string;
  commonSideEffects: string;
  combinesWithAvoid: string;
};

// Valores típicos de referencia — el usuario los puede ajustar libremente.
// No es consejo médico: solo agiliza el llenado del formulario (ver Constitución del Producto).
export const PEPTIDE_PROFILES: PeptideProfile[] = [
  {
    name: "BPC-157",
    route: "Subcutánea",
    commonDose: "250",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "3",
    frequency: "1-2x al día",
    categories: ["recuperacion", "intestinal"],
    tags: ["Reparación tisular", "Salud digestiva"],
    description:
      "Pentadecapéptido derivado de una proteína gástrica. Conocido por sus propiedades de reparación tisular y salud digestiva.",
    halfLife: "~15 min (estudios en animales; sin dato humano formal)",
    halfLifeConfidence: "bajo",
    howItWorks:
      "Estabiliza y protege el revestimiento gástrico e intestinal, y favorece la formación de nuevos vasos sanguíneos en tejido dañado (tendón, ligamento, músculo, intestino).",
    mostReported: [
      "Recuperación más rápida de lesiones de tendón/ligamento",
      "Menos molestias digestivas",
      "Menor inflamación percibida tras el ejercicio",
    ],
    evidenceLevel:
      "Muy estudiado en modelos animales; en humanos hay ensayos clínicos tempranos para colitis, pero la mayoría del reporte viene de uso informal.",
    commonSideEffects: "Generalmente bien tolerado; algunos reportan enrojecimiento en el punto de inyección o mareo leve.",
    combinesWithAvoid:
      "Se combina muy seguido con TB-500 para recuperación. No hay interacción grave conocida con otros péptidos de esta lista.",
  },
  {
    name: "TB-500",
    route: "Subcutánea",
    commonDose: "2",
    doseUnit: "mg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "2x por semana",
    categories: ["recuperacion"],
    tags: ["Recuperación", "Movilidad"],
    description:
      "Fragmento sintético de la timosina beta-4. Promueve la cicatrización, regeneración celular y movilidad.",
    halfLife: "~2-3 horas (estimado, sin PK humana formal)",
    halfLifeConfidence: "bajo",
    howItWorks:
      "Versión sintética de la timosina beta-4; promueve la migración celular y la formación de nuevos vasos sanguíneos para acelerar la cicatrización de tejidos.",
    mostReported: ["Mejor movilidad articular", "Recuperación más rápida tras lesión", "Menos rigidez muscular"],
    evidenceLevel:
      "Estudios preclínicos amplios; en humanos la evidencia es mayormente de reporte de clínicas y uso informal, sin ensayos clínicos grandes.",
    commonSideEffects: "Cansancio leve o dolor de cabeza los primeros días; poco frecuente y transitorio.",
    combinesWithAvoid:
      "Va bien con BPC-157 (combo clásico de recuperación). No se recomienda mezclarlo con otro péptido de acción similar sin espaciar dosis.",
  },
  {
    name: "Semaglutida",
    route: "Subcutánea",
    commonDose: "0.25",
    doseUnit: "mg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x por semana",
    categories: ["peso"],
    tags: ["Control de peso"],
    description:
      "Agonista del receptor GLP-1. Reduce el apetito, retrasa el vaciamiento gástrico y mejora la sensibilidad a la insulina.",
    halfLife: "~1 semana",
    halfLifeConfidence: "alto",
    howItWorks:
      "Imita al GLP-1 natural: reduce el apetito, enlentece el vaciado del estómago y mejora cómo el cuerpo maneja el azúcar en sangre.",
    mostReported: ["Reducción notable del apetito", "Pérdida de peso sostenida semana a semana", "Menos antojos de comida"],
    evidenceLevel: "Evidencia fuerte: aprobado por la FDA (Wegovy/Ozempic) con decenas de ensayos clínicos grandes en humanos.",
    commonSideEffects: "Náuseas, estreñimiento o reflujo, sobre todo al subir de dosis; suele mejorar con el tiempo.",
    combinesWithAvoid: "Se combina a veces con Cagrilintide (efecto complementario). Evita subir dosis rápido si ya tienes náuseas.",
  },
  {
    name: "Tirzepatida",
    route: "Subcutánea",
    commonDose: "2.5",
    doseUnit: "mg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x por semana",
    categories: ["peso"],
    tags: ["Control de peso"],
    description:
      "Agonista dual GIP/GLP-1. Apoya el control de peso y mejora la sensibilidad a la insulina.",
    halfLife: "~5 días",
    halfLifeConfidence: "alto",
    howItWorks:
      "Activa a la vez los receptores GIP y GLP-1, lo que potencia el control del apetito y la sensibilidad a la insulina más que un GLP-1 solo.",
    mostReported: ["Pérdida de peso mayor que con GLP-1 solo", "Apetito muy reducido", "Mejor control de glucosa"],
    evidenceLevel: "Evidencia fuerte: aprobado por la FDA (Mounjaro/Zepbound) con ensayos clínicos extensos.",
    commonSideEffects: "Náuseas, diarrea o estreñimiento, más intensos al subir dosis.",
    combinesWithAvoid: "No se combina con otro GLP-1/GIP a la vez (semaglutida, retatrutida). Sube de dosis despacio para tolerarlo mejor.",
  },
  {
    name: "Retatrutida",
    route: "Subcutánea",
    commonDose: "2",
    doseUnit: "mg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x por semana",
    categories: ["peso"],
    tags: ["Control de peso"],
    description: "Agonista triple GIP/GLP-1/glucagón, en investigación para control de peso.",
    halfLife: "~6 días",
    halfLifeConfidence: "alto",
    howItWorks:
      "Activa tres receptores a la vez (GIP, GLP-1 y glucagón), sumando el efecto de quema de energía del glucagón al control de apetito de los otros dos.",
    mostReported: ["Pérdida de peso muy marcada en estudios", "Apetito muy controlado", "Más energía reportada por algunos usuarios"],
    evidenceLevel:
      "En fase de investigación (fase 3); los datos de fase 2 son sólidos pero aún no está aprobado por ninguna agencia regulatoria.",
    commonSideEffects: "Náuseas y molestias digestivas similares a otros agonistas GLP-1, generalmente dosis-dependientes.",
    combinesWithAvoid: "No combinar con otro agonista GLP-1/GIP/glucagón a la vez.",
  },
  {
    name: "Cagrilintide",
    route: "Subcutánea",
    commonDose: "0.5",
    doseUnit: "mg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x por semana",
    categories: ["peso"],
    tags: ["Control de peso"],
    description:
      "Análogo de la amilina de acción prolongada. Suele combinarse con un GLP-1 para el control de peso.",
    halfLife: "~7 días",
    halfLifeConfidence: "alto",
    howItWorks: "Imita a la amilina, una hormona que aumenta la saciedad y ayuda a comer porciones más pequeñas sin sentir tanta hambre.",
    mostReported: ["Mayor sensación de saciedad", "Complementa la pérdida de peso de un GLP-1", "Menos picoteo entre comidas"],
    evidenceLevel: "Ensayos clínicos en curso (incluida la combinación CagriSema); prometedor pero todavía no aprobado en solitario.",
    commonSideEffects: "Náuseas leves, similares a los GLP-1, sobre todo al iniciar.",
    combinesWithAvoid: "Se combina explícitamente con Semaglutida (CagriSema). Evita sumarlo a otro supresor de apetito fuerte sin ir despacio.",
  },
  {
    name: "AOD-9604",
    route: "Subcutánea",
    commonDose: "300",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día",
    categories: ["peso"],
    tags: ["Metabolismo"],
    description: "Fragmento de la hormona de crecimiento asociado al metabolismo de las grasas.",
    halfLife: "~3-4 min (estudios preclínicos)",
    halfLifeConfidence: "bajo",
    howItWorks:
      "Fragmento de la hormona de crecimiento diseñado para conservar el efecto quema-grasa sin elevar el azúcar en sangre ni el crecimiento de tejido.",
    mostReported: ["Reducción de grasa localizada (reportada, no siempre consistente)", "Sin efecto notorio en apetito"],
    evidenceLevel: "Llegó a fase 2 en ensayos clínicos para obesidad pero no logró superioridad frente a placebo; evidencia limitada.",
    commonSideEffects: "Generalmente bien tolerado; pocos reportes de efectos secundarios relevantes.",
    combinesWithAvoid: "Se usa a veces junto a péptidos de GH (CJC-1295/Ipamorelina) por su origen común, sin evidencia sólida de sinergia.",
  },
  {
    name: "Adipotide (FTPP)",
    route: "Subcutánea",
    commonDose: "1",
    doseUnit: "mg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "3x por semana",
    categories: ["peso"],
    tags: ["Control de peso"],
    description:
      "Péptido pro-apoptótico dirigido a los vasos sanguíneos del tejido adiposo blanco. Reduce grasa abdominal.",
    halfLife: "Sin dato confiable en humanos",
    halfLifeConfidence: "sin-dato",
    howItWorks: "Induce la muerte de las células que alimentan los vasos sanguíneos del tejido graso blanco, cortando su aporte de sangre.",
    mostReported: ["Reducción de grasa abdominal (solo en estudios animales)"],
    evidenceLevel: "Sin dato confiable en humanos — solo estudios en monos y ratones; no hay ensayos clínicos en personas.",
    commonSideEffects: "Puede afectar la función renal en estudios animales; sin datos de seguridad en humanos.",
    combinesWithAvoid: "No hay datos de interacción en humanos — usar con máxima precaución dado lo limitado de la evidencia.",
  },
  {
    name: "5-Amino-1MQ",
    route: "Oral",
    commonDose: "50",
    doseUnit: "mg",
    vialAmount: "-",
    vialUnit: "mg",
    bacWater: "0",
    frequency: "1x al día",
    categories: ["peso"],
    tags: ["Metabolismo"],
    description:
      "Inhibidor de la enzima NNMT (nicotinamida N-metiltransferasa). Aumenta los niveles celulares de NAD+.",
    halfLife: "~4-7 horas (estudios en animales)",
    halfLifeConfidence: "bajo",
    howItWorks: "Bloquea la enzima NNMT, lo que deja más NAD+ disponible en la célula y acelera el metabolismo, sobre todo en el tejido graso.",
    mostReported: ["Apoyo al metabolismo", "Se reporta junto a rutinas de pérdida de grasa"],
    evidenceLevel:
      "Estudios preclínicos (animales); no es técnicamente un péptido sino una molécula pequeña, y falta evidencia clínica en humanos.",
    commonSideEffects: "Datos de seguridad en humanos muy limitados.",
    combinesWithAvoid: "Se combina a veces con NAD+ o péptidos de pérdida de peso; sin estudios formales de esa combinación.",
  },
  {
    name: "Ipamorelina",
    route: "Subcutánea",
    commonDose: "200",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2.5",
    frequency: "1-2x al día",
    categories: ["musculo_gh"],
    tags: ["Hormona de crecimiento"],
    description:
      "Secretagogo selectivo de hormona de crecimiento, con un perfil de efectos secundarios más suave que otros análogos.",
    halfLife: "~2 horas",
    halfLifeConfidence: "alto",
    howItWorks: "Estimula la liberación de hormona de crecimiento de forma selectiva, sin tocar cortisol, prolactina ni otras hormonas.",
    mostReported: ["Mejor calidad de sueño", "Recuperación muscular", "Menos hambre que otros GHRP"],
    evidenceLevel: "Estudios clínicos moderados en humanos que confirman su selectividad frente a otros GHRP.",
    commonSideEffects: "Hormigueo o enrojecimiento leve en el punto de inyección; menos retención de líquidos que GHRP-2/6.",
    combinesWithAvoid: "Combo clásico con CJC-1295 (sinergia GHRH+GHRP). No combinar con otro GHRP a la vez.",
  },
  {
    name: "CJC-1295",
    route: "Subcutánea",
    commonDose: "100",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día",
    categories: ["musculo_gh"],
    tags: ["Hormona de crecimiento"],
    description: "Análogo de acción prolongada de la hormona liberadora de GH. Suele combinarse con Ipamorelina.",
    halfLife: "~30 min (sin DAC) — la versión con DAC llega a 6-8 días; confirma cuál tienes",
    halfLifeConfidence: "medio",
    howItWorks: "Análogo de la hormona liberadora de GH (GHRH); hace que la pituitaria libere más hormona de crecimiento de forma pulsátil.",
    mostReported: ["Mejor recuperación", "Sueño más profundo", "Cambios en composición corporal a mediano plazo"],
    evidenceLevel: "Evidencia moderada a fuerte según la versión (con DAC tiene más respaldo por su uso prolongado).",
    commonSideEffects: "Enrojecimiento en el punto de inyección, retención de líquidos leve, hormigueo en manos.",
    combinesWithAvoid: "Va con Ipamorelina o GHRP-2/6. No combinar dos GHRH a la vez.",
  },
  {
    name: "MK-677 (Ibutamoren)",
    route: "Oral",
    commonDose: "25",
    doseUnit: "mg",
    vialAmount: "-",
    vialUnit: "mg",
    bacWater: "0",
    frequency: "1x al día",
    categories: ["musculo_gh"],
    tags: ["Hormona de crecimiento"],
    description:
      "Secretagogo no peptídico de GH activo por vía oral. Imita la acción de la grelina sobre los receptores de GH.",
    halfLife: "~4-6 horas (efecto sostenido reportado hasta 24 h)",
    halfLifeConfidence: "medio",
    howItWorks: "Imita a la grelina y estimula la liberación de GH por vía oral, sin necesidad de inyección.",
    mostReported: ["Más apetito", "Mejor sueño", "Aumento de masa magra a mediano plazo"],
    evidenceLevel: "Evidencia clínica sólida en varios ensayos controlados en humanos.",
    commonSideEffects: "Aumento del apetito, retención de líquidos, entumecimiento de manos; puede subir la glucosa en ayunas.",
    combinesWithAvoid: "Se combina con péptidos de recuperación (BPC-157/TB-500). Precaución si ya tienes resistencia a la insulina.",
  },
  {
    name: "Sermorelina",
    route: "Subcutánea",
    commonDose: "200",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día",
    categories: ["musculo_gh", "sueno"],
    tags: ["Hormona de crecimiento"],
    description:
      "Análogo de la hormona liberadora de GH. Suele usarse antes de dormir por su efecto sobre el sueño profundo.",
    halfLife: "~11-12 min",
    halfLifeConfidence: "alto",
    howItWorks:
      "Versión corta de la GHRH natural; estimula al cuerpo a liberar su propia GH de forma pulsátil y fisiológica.",
    mostReported: ["Sueño más profundo", "Mejor recuperación nocturna", "Composición corporal a largo plazo"],
    evidenceLevel: "Evidencia fuerte: usada clínicamente durante décadas para deficiencia de GH.",
    commonSideEffects: "Enrojecimiento en el punto de inyección, dolor de cabeza ocasional.",
    combinesWithAvoid: "Se combina con GHRP (Ipamorelina, GHRP-2). No duplicar con otro GHRH el mismo día.",
  },
  {
    name: "Tesamorelina",
    route: "Subcutánea",
    commonDose: "1",
    doseUnit: "mg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día",
    categories: ["musculo_gh", "peso"],
    tags: ["Hormona de crecimiento"],
    description:
      "Análogo de la hormona liberadora de GH, estudiado especialmente para la reducción de grasa visceral.",
    halfLife: "~8-11 min",
    halfLifeConfidence: "alto",
    howItWorks:
      "Análogo de la GHRH aprobado clínicamente; estimula la liberación pulsátil de GH, con foco estudiado en la grasa visceral.",
    mostReported: ["Reducción de grasa abdominal/visceral", "Mejor definición muscular"],
    evidenceLevel: "Evidencia fuerte: aprobado por la FDA (Egrifta) para lipodistrofia asociada a VIH.",
    commonSideEffects: "Enrojecimiento en el punto de inyección, dolor articular ocasional, hinchazón leve.",
    combinesWithAvoid: "Se combina con GHRP para potenciar el pulso de GH. Evitar en quienes ya tienen niveles altos de IGF-1.",
  },
  {
    name: "GHK-Cu",
    route: "Subcutánea",
    commonDose: "1",
    doseUnit: "mg",
    vialAmount: "50",
    vialUnit: "mg",
    bacWater: "10",
    frequency: "1x al día",
    categories: ["piel_belleza", "longevidad", "recuperacion"],
    tags: ["Piel", "Antienvejecimiento"],
    description:
      "Complejo péptido-cobre presente naturalmente en el cuerpo. Muy usado en cosmética por su efecto en colágeno y cicatrización; también tópico.",
    halfLife: "~25-35 min (estimado, sin PK humana formal)",
    halfLifeConfidence: "bajo",
    howItWorks: "Complejo natural péptido-cobre que activa genes de reparación de la piel y estimula la producción de colágeno.",
    mostReported: ["Piel más firme y con mejor textura", "Cicatrización más rápida", "Menos líneas finas (uso tópico)"],
    evidenceLevel: "Muy estudiado en cosmética (más de 40 años); en uso inyectado la evidencia es más limitada.",
    commonSideEffects: "Irritación leve en piel si es tópico; enrojecimiento en el punto de inyección si es subcutáneo.",
    combinesWithAvoid:
      "Se combina en blends populares (con BPC-157/TB-500 tipo 'GLOW'). No mezclar con otros complejos de cobre sin espaciar.",
  },
  {
    name: "MOTS-c",
    route: "Subcutánea",
    commonDose: "5",
    doseUnit: "mg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "3x por semana",
    categories: ["longevidad", "peso"],
    tags: ["Metabolismo", "Longevidad"],
    description:
      "Péptido derivado de la mitocondria. En tendencia por su posible rol en el metabolismo de la glucosa y la respuesta al estrés celular.",
    halfLife: "Sin dato confiable en humanos",
    halfLifeConfidence: "sin-dato",
    howItWorks: "Péptido producido dentro de la mitocondria que ayuda a regular cómo el cuerpo usa la energía y la sensibilidad a la insulina.",
    mostReported: ["Más energía durante el ejercicio", "Apoyo al metabolismo de la glucosa"],
    evidenceLevel: "Sin dato confiable en humanos — descubierto en 2015, la mayoría de la evidencia es preclínica (animal/celular).",
    commonSideEffects: "Datos de seguridad en humanos muy limitados.",
    combinesWithAvoid: "Se combina a veces con NAD+ por su rol mitocondrial compartido; sin estudios formales de esa combinación.",
  },
  {
    name: "Epitalon",
    route: "Subcutánea",
    commonDose: "5",
    doseUnit: "mg",
    vialAmount: "50",
    vialUnit: "mg",
    bacWater: "5",
    frequency: "1x al día (en ciclos)",
    categories: ["longevidad", "sueno"],
    tags: ["Longevidad"],
    description:
      "Péptido sintético derivado de la glándula pineal. Estudiado por su posible relación con la regulación del reloj biológico y la telomerasa.",
    halfLife: "Sin dato confiable en ninguna especie",
    halfLifeConfidence: "sin-dato",
    howItWorks:
      "Péptido sintético inspirado en un compuesto de la glándula pineal; se estudia su rol en el reloj biológico y la telomerasa.",
    mostReported: ["Mejor calidad de sueño", "Sensación de mayor energía tras el ciclo"],
    evidenceLevel:
      "Sin dato confiable en ninguna especie a nivel de ensayo clínico riguroso — la mayoría del respaldo viene de investigación rusa antigua, difícil de verificar.",
    commonSideEffects: "Sin reportes relevantes de efectos secundarios; datos de seguridad limitados.",
    combinesWithAvoid: "Se usa a menudo en ciclos cortos aislados, sin combinarlo con otros péptidos de longevidad al mismo tiempo.",
  },
  {
    name: "DSIP",
    route: "Subcutánea",
    commonDose: "100",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x antes de dormir",
    categories: ["sueno"],
    tags: ["Sueño"],
    description: "Péptido inductor del sueño delta (Delta Sleep-Inducing Peptide). Se usa antes de dormir.",
    halfLife: "~15-25 min (estimado)",
    halfLifeConfidence: "medio",
    howItWorks: "Péptido asociado al sueño profundo (delta); su mecanismo exacto en humanos no está del todo claro.",
    mostReported: ["Dormirse más rápido", "Sueño más profundo y reparador"],
    evidenceLevel:
      "Evidencia moderada en estudios pequeños; su receptor específico aún no se ha identificado con certeza.",
    commonSideEffects: "Somnolencia diurna si la dosis es alta; generalmente bien tolerado.",
    combinesWithAvoid: "Se usa solo, justo antes de dormir. Evitar combinarlo con otros sedantes o alcohol.",
  },
  {
    name: "Selank",
    route: "Intranasal",
    commonDose: "300",
    doseUnit: "mcg",
    vialAmount: "-",
    vialUnit: "mg",
    bacWater: "0",
    frequency: "1-2x al día",
    categories: ["cognicion", "sueno"],
    tags: ["Ansiolítico", "Enfoque"],
    description:
      "Péptido ansiolítico de origen ruso. Se asocia con calma mental y enfoque sin sedación.",
    halfLife: "Sin dato confiable (fuentes muy dispares)",
    halfLifeConfidence: "sin-dato",
    howItWorks: "Derivado de la tuftsina; actúa como ansiolítico sin la sedación típica de las benzodiazepinas.",
    mostReported: ["Menos ansiedad", "Mejor enfoque bajo estrés", "Sin sensación de sedación"],
    evidenceLevel: "Estudios clínicos moderados, mayormente rusos; poco replicados fuera de Rusia.",
    commonSideEffects: "Generalmente bien tolerado; congestión nasal leve si es intranasal.",
    combinesWithAvoid: "Se combina seguido con Semax (calma + enfoque). No combinar con otros ansiolíticos sin supervisión.",
  },
  {
    name: "Semax",
    route: "Intranasal",
    commonDose: "300",
    doseUnit: "mcg",
    vialAmount: "-",
    vialUnit: "mg",
    bacWater: "0",
    frequency: "1-2x al día",
    categories: ["cognicion"],
    tags: ["Nootrópico"],
    description: "Péptido nootrópico derivado de la ACTH. Estudiado por su efecto en memoria y concentración.",
    halfLife: "Sin dato confiable (fuentes muy dispares)",
    halfLifeConfidence: "sin-dato",
    howItWorks:
      "Derivado de un fragmento de la ACTH; se asocia con mayor factor neurotrófico (BDNF) y mejor plasticidad cerebral.",
    mostReported: ["Más concentración", "Mejor memoria de trabajo", "Sensación de mayor claridad mental"],
    evidenceLevel: "Más de 30 años de uso clínico en Rusia, pero pocos ensayos controlados fuera de ese país.",
    commonSideEffects: "Irritación nasal leve si es intranasal; puede dar sensación de sobreestimulación en dosis altas.",
    combinesWithAvoid: "Se combina con Selank para balancear estímulo y calma. Evitar combinarlo con otros estimulantes fuertes.",
  },
  {
    name: "PT-141 (Bremelanotida)",
    route: "Subcutánea",
    commonDose: "1",
    doseUnit: "mg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "Según necesidad",
    categories: ["libido"],
    tags: ["Libido"],
    description: "Activador de receptores de melanocortina. Usado para la libido y función sexual.",
    halfLife: "~2.7 horas",
    halfLifeConfidence: "alto",
    howItWorks:
      "Activa receptores de melanocortina en el cerebro (no en el flujo sanguíneo), lo que estimula el deseo sexual de forma central.",
    mostReported: ["Mayor deseo sexual", "Efecto más notorio en mujeres (uso aprobado) que en hombres"],
    evidenceLevel:
      "Evidencia fuerte: aprobado por la FDA (Vyleesi) para el trastorno de deseo sexual hipoactivo en mujeres.",
    commonSideEffects: "Náuseas (frecuentes, sobre todo en las primeras dosis), rubor facial, dolor de cabeza.",
    combinesWithAvoid: "No lo combines con Melanotan II el mismo día (mecanismo similar, mayor riesgo de náuseas).",
  },
  {
    name: "Melanotan II",
    route: "Subcutánea",
    commonDose: "250",
    doseUnit: "mcg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "3x por semana",
    categories: ["piel_belleza", "libido"],
    tags: ["Bronceado"],
    description: "Análogo de la hormona estimulante de melanocitos. Conocido por su efecto bronceador.",
    halfLife: "~1-2 horas",
    halfLifeConfidence: "medio",
    howItWorks: "Activa varios receptores de melanocortina a la vez: broncea la piel y también puede estimular el deseo sexual.",
    mostReported: ["Bronceado más rápido y duradero", "Aumento del libido en algunos usuarios"],
    evidenceLevel: "Evidencia moderada; no tiene aprobación regulatoria (a diferencia de PT-141, que es su derivado aprobado).",
    commonSideEffects: "Náuseas frecuentes al inicio, oscurecimiento de lunares, sofocos; requiere protección solar igual.",
    combinesWithAvoid: "No combinar con PT-141 el mismo día. Empezar con dosis muy bajas para evaluar tolerancia a las náuseas.",
  },
  {
    name: "Timosina Alfa-1",
    route: "Subcutánea",
    commonDose: "1.6",
    doseUnit: "mg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "2x por semana",
    categories: ["inmunidad"],
    tags: ["Inmunidad"],
    description: "Péptido inmunomodulador natural del timo. Estudiado para el soporte del sistema inmune.",
    halfLife: "~2 horas",
    halfLifeConfidence: "alto",
    howItWorks: "Péptido natural del timo que ayuda a regular y modular la respuesta del sistema inmune.",
    mostReported: ["Menos resfriados/infecciones reportadas", "Recuperación más rápida tras enfermedad"],
    evidenceLevel: "Evidencia moderada: aprobado en más de 35 países para hepatitis B, aunque no por la FDA en EE. UU.",
    commonSideEffects: "Generalmente bien tolerado; enrojecimiento leve en el punto de inyección.",
    combinesWithAvoid: "Se usa en protocolos de soporte inmune junto a KPV. Sin interacciones graves conocidas.",
  },
  {
    name: "KPV",
    route: "Subcutánea",
    commonDose: "500",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día",
    categories: ["intestinal", "piel_belleza"],
    tags: ["Antiinflamatorio"],
    description: "Fragmento de la alfa-MSH con propiedades antiinflamatorias. Usado en salud intestinal y de piel.",
    halfLife: "~1-2 horas (estimado, sin PK humana formal)",
    halfLifeConfidence: "bajo",
    howItWorks: "Fragmento de la alfa-MSH con potente efecto antiinflamatorio, sin el efecto bronceador de la molécula completa.",
    mostReported: ["Menos inflamación intestinal", "Mejora en piel inflamada", "Cicatrización de heridas"],
    evidenceLevel:
      "Estudios preclínicos sólidos para enfermedad inflamatoria intestinal; evidencia clínica en humanos todavía limitada.",
    commonSideEffects: "Generalmente muy bien tolerado, incluso por vía oral.",
    combinesWithAvoid: "Se combina con BPC-157 para salud intestinal. Sin interacciones graves conocidas.",
  },
  {
    name: "GHRP-2",
    route: "Subcutánea",
    commonDose: "200",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1-2x al día",
    categories: ["musculo_gh"],
    tags: ["Hormona de crecimiento"],
    description: "Hexapéptido sintético estimulador de GH, potente y con menos efecto sobre el apetito que GHRP-6.",
    halfLife: "~15-30 min",
    halfLifeConfidence: "medio",
    howItWorks: "Se une a receptores de grelina en la pituitaria y estimula una liberación potente de hormona de crecimiento.",
    mostReported: ["Aumento de masa magra", "Mejor recuperación", "Menos hambre que GHRP-6"],
    evidenceLevel: "Estudios pequeños y experiencia de clínicas; aprobado en Japón solo como agente diagnóstico, no terapéutico.",
    commonSideEffects: "Hambre moderada, retención de líquidos leve, hormigueo en el punto de inyección.",
    combinesWithAvoid: "Va con CJC-1295. No combinar dos GHRP a la vez.",
  },
  {
    name: "GHRP-6",
    route: "Subcutánea",
    commonDose: "200",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1-2x al día",
    categories: ["musculo_gh"],
    tags: ["Hormona de crecimiento", "Apetito"],
    description: "Hexapéptido estimulador de GH, conocido por su fuerte efecto sobre el apetito.",
    halfLife: "~20-30 min",
    halfLifeConfidence: "medio",
    howItWorks: "Igual que GHRP-2, pero con una señal de hambre mucho más marcada.",
    mostReported: ["Mucho apetito (útil en volumen)", "Apoyo muscular", "Recuperación"],
    evidenceLevel: "Estudios pequeños y experiencia de clínicas.",
    commonSideEffects: "Hambre intensa, retención de líquidos, hormigueo; sube cortisol y prolactina.",
    combinesWithAvoid: "Va con CJC-1295. No combinar dos GHRP a la vez.",
  },
  {
    name: "Hexarelin",
    route: "Subcutánea",
    commonDose: "100",
    doseUnit: "mcg",
    vialAmount: "2",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día",
    categories: ["musculo_gh"],
    tags: ["Hormona de crecimiento"],
    description: "El GHRP más potente para liberar GH; también estudiado por posibles efectos protectores del corazón.",
    halfLife: "~60-70 min",
    halfLifeConfidence: "medio",
    howItWorks:
      "Estimula receptores de grelina de forma muy potente y activa también receptores CD36 con efecto cardioprotector reportado en estudios.",
    mostReported: ["Fuerte liberación de GH", "Recuperación muscular", "Efecto reportado sobre el corazón (preclínico)"],
    evidenceLevel: "Estudios preclínicos sólidos en lo cardioprotector; en humanos la evidencia es más limitada y de uso informal.",
    commonSideEffects: "Desensibilización con uso prolongado (pierde efecto con el tiempo), hambre, retención de líquidos.",
    combinesWithAvoid: "Se rota con otros GHRP para evitar la desensibilización. No usar todos los días por periodos largos.",
  },
  {
    name: "HGH (Somatropina)",
    route: "Subcutánea",
    commonDose: "2",
    doseUnit: "UI",
    vialAmount: "10",
    vialUnit: "UI",
    bacWater: "1",
    frequency: "1x al día",
    categories: ["musculo_gh"],
    tags: ["Hormona de crecimiento"],
    description: "Hormona de crecimiento recombinante, idéntica a la que produce tu propia pituitaria.",
    halfLife: "~2-4 horas",
    halfLifeConfidence: "alto",
    howItWorks:
      "Actúa directamente sobre receptores de GH en todo el cuerpo, aumentando la producción de IGF-1 y el crecimiento/reparación de tejidos.",
    mostReported: ["Mejor composición corporal", "Recuperación más rápida", "Piel y sueño reportados como beneficio"],
    evidenceLevel: "Evidencia fuerte: aprobado por la FDA desde 1985, con más de 30 años de uso clínico documentado.",
    commonSideEffects: "Retención de líquidos, hormigueo en manos, posible resistencia a la insulina con uso prolongado.",
    combinesWithAvoid: "No se combina con otros secretagogos de GH (CJC-1295, Ipamorelina) en el mismo protocolo — son mecanismos redundantes.",
  },
  {
    name: "HGH Fragment 176-191",
    route: "Subcutánea",
    commonDose: "250",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día",
    categories: ["peso"],
    tags: ["Metabolismo"],
    description: "Fragmento de la hormona de crecimiento enfocado en el efecto quema-grasa, sin el efecto sobre el crecimiento de tejidos.",
    halfLife: "Sin dato confiable en humanos",
    halfLifeConfidence: "sin-dato",
    howItWorks: "Actúa sobre el tejido graso imitando la parte de la GH que rompe grasa (lipólisis), sin activar IGF-1.",
    mostReported: ["Reducción de grasa localizada (reportada)", "Sin afectar el apetito"],
    evidenceLevel: "Estudios preclínicos y algunos en humanos, pero de baja calidad metodológica; evidencia limitada.",
    commonSideEffects: "Generalmente bien tolerado; pocos reportes de efectos relevantes.",
    combinesWithAvoid: "Se combina a veces con AOD-9604 (mecanismo similar) — no hay evidencia clara de que sumarlos aporte más.",
  },
  {
    name: "IGF-1 LR3",
    route: "Subcutánea",
    commonDose: "50",
    doseUnit: "mcg",
    vialAmount: "1",
    vialUnit: "mg",
    bacWater: "1",
    frequency: "1x al día",
    categories: ["musculo_gh"],
    tags: ["Hormona de crecimiento"],
    description: "Versión modificada del IGF-1 con vida media mucho más larga, usada para crecimiento y recuperación muscular.",
    halfLife: "~20-30 horas",
    halfLifeConfidence: "medio",
    howItWorks: "Se une con menos afinidad a las proteínas transportadoras de IGF-1, quedando más tiempo libre y activo en el cuerpo.",
    mostReported: ["Aumento de masa muscular", "Mejor recuperación tras entreno intenso"],
    evidenceLevel: "Estudios pequeños y experiencia de clínicas/comunidad; sin ensayos clínicos grandes en humanos.",
    commonSideEffects: "Hipoglucemia (bajada de azúcar), retención de líquidos, hormigueo.",
    combinesWithAvoid: "Se usa a veces tras el entreno junto a péptidos de recuperación. Vigilar la glucosa si se combina con otros compuestos que la bajen.",
  },
  {
    name: "PEG-MGF",
    route: "Subcutánea",
    commonDose: "200",
    doseUnit: "mcg",
    vialAmount: "2",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "2-3x por semana",
    categories: ["musculo_gh", "recuperacion"],
    tags: ["Recuperación muscular"],
    description: "Versión pegilada (de acción prolongada) del factor de crecimiento mecánico, activado naturalmente por el estiramiento o daño muscular.",
    halfLife: "~24-72 horas (versión pegilada)",
    halfLifeConfidence: "medio",
    howItWorks:
      "Activa células satélite del músculo para reparar y hacer crecer fibras dañadas, por una vía distinta a la del IGF-1 clásico.",
    mostReported: ["Reparación muscular localizada", "Se usa tras entrenos de fuerza intensos"],
    evidenceLevel: "Estudios preclínicos y experiencia de clínicas/comunidad; poca evidencia clínica formal en humanos.",
    commonSideEffects: "Dolor o enrojecimiento en el punto de inyección, especialmente si se aplica en el músculo entrenado.",
    combinesWithAvoid: "Se combina con IGF-1 LR3 en protocolos de recuperación muscular. Espaciar de otros péptidos inyectados en la misma zona.",
  },
  {
    name: "Gonadorelina",
    route: "Subcutánea",
    commonDose: "100",
    doseUnit: "mcg",
    vialAmount: "2",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "2-3x por semana",
    categories: ["libido"],
    tags: ["Fertilidad", "TRT"],
    description: "Versión sintética de la GnRH natural; estimula al cuerpo a producir sus propias hormonas sexuales.",
    halfLife: "~10-40 min",
    halfLifeConfidence: "medio",
    howItWorks: "Estimula la pituitaria para liberar LH y FSH, lo que mantiene activa la producción natural de testosterona en los testículos.",
    mostReported: ["Mantiene la función testicular durante la terapia de testosterona", "Apoyo a la fertilidad"],
    evidenceLevel: "Uso clínico bien documentado para mantener el eje hormonal durante TRT; también aprobado para diagnóstico de función pituitaria.",
    commonSideEffects: "Dolor de cabeza leve, enrojecimiento en el punto de inyección.",
    combinesWithAvoid: "Se usa junto a la terapia de testosterona (TRT) para no perder función testicular. No sustituye al HCG si ya lo usas — cumplen un rol parecido.",
  },
  {
    name: "HCG",
    route: "Subcutánea",
    commonDose: "250",
    doseUnit: "UI",
    vialAmount: "5000",
    vialUnit: "UI",
    bacWater: "2",
    frequency: "2-3x por semana",
    categories: ["libido"],
    tags: ["Fertilidad", "TRT"],
    description: "Hormona que imita a la LH; en hombres estimula la producción de testosterona en los testículos.",
    halfLife: "~24-36 horas",
    halfLifeConfidence: "alto",
    howItWorks: "Se une a los mismos receptores que la LH en el testículo, manteniendo su tamaño y producción de testosterona activa.",
    mostReported: ["Mantiene el volumen testicular durante TRT", "Apoyo a la fertilidad", "Menos 'apagón' hormonal al parar TRT"],
    evidenceLevel: "Evidencia fuerte: aprobado por la FDA desde hace décadas para infertilidad e hipogonadismo.",
    commonSideEffects: "Acné, retención de líquidos, cambios de humor a dosis altas.",
    combinesWithAvoid: "Se combina con TRT (testosterona) para mantener la función testicular. No es necesario sumarlo a Gonadorelina — cumplen un rol parecido.",
  },
  {
    name: "Kisspeptina",
    route: "Subcutánea",
    commonDose: "100",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "Según protocolo",
    categories: ["libido"],
    tags: ["Fertilidad"],
    description: "Neuropéptido regulador maestro del eje reproductivo; actúa por encima incluso de la GnRH.",
    halfLife: "~4-28 min (varía según el fragmento)",
    halfLifeConfidence: "medio",
    howItWorks:
      "Activa las neuronas que liberan GnRH, iniciando toda la cascada hormonal reproductiva de forma más 'fisiológica' que un análogo directo.",
    mostReported: ["Apoyo a la fertilidad", "Interés en investigación como alternativa a la GnRH"],
    evidenceLevel: "Estudios pequeños en humanos, en fase de investigación para fertilidad; todavía no es un tratamiento estándar.",
    commonSideEffects: "Enrojecimiento en el punto de inyección; datos de seguridad a largo plazo limitados.",
    combinesWithAvoid: "Es experimental — evitar combinarla con otros moduladores hormonales sin supervisión médica.",
  },
  {
    name: "Oxitocina",
    route: "Intranasal",
    commonDose: "20",
    doseUnit: "UI",
    vialAmount: "-",
    vialUnit: "mg",
    bacWater: "0",
    frequency: "Según necesidad",
    categories: ["libido", "cognicion"],
    tags: ["Vínculo", "Bienestar emocional"],
    description: "Hormona conocida como la 'del vínculo'; en dosis intranasal se estudia su efecto en la conexión social y emocional.",
    halfLife: "~3-5 min",
    halfLifeConfidence: "alto",
    howItWorks: "Actúa sobre receptores en el cerebro relacionados con el apego, la confianza y la regulación emocional.",
    mostReported: ["Mayor sensación de cercanía/conexión", "Menos ansiedad social reportada"],
    evidenceLevel:
      "Aprobada por la FDA para uso obstétrico (parto); el uso intranasal para efectos sociales/emocionales está en investigación, no aprobado con ese fin.",
    commonSideEffects: "Congestión nasal leve, dolor de cabeza ocasional.",
    combinesWithAvoid: "Se usa sola. Sin interacciones relevantes conocidas con otros péptidos de esta lista.",
  },
  {
    name: "NAD+",
    route: "Subcutánea",
    commonDose: "100",
    doseUnit: "mg",
    vialAmount: "500",
    vialUnit: "mg",
    bacWater: "5",
    frequency: "2-3x por semana",
    categories: ["longevidad"],
    tags: ["Longevidad", "Energía"],
    description: "Coenzima esencial para la producción de energía celular y la reparación del ADN; sus niveles bajan con la edad.",
    halfLife: "Variable (horas a días, según la vía)",
    halfLifeConfidence: "bajo",
    howItWorks: "Recarga el 'combustible' que usan las mitocondrias y ciertas enzimas (sirtuinas) relacionadas con el envejecimiento celular.",
    mostReported: ["Más energía y claridad mental", "Mejor recuperación reportada", "Interés por su rol en longevidad"],
    evidenceLevel:
      "Evidencia moderada de que los niveles bajan con la edad y se asocian a enfermedades; la suplementación directa en humanos tiene estudios pequeños.",
    commonSideEffects: "Si se aplica rápido por vía IV puede dar opresión en el pecho o rubor; subcutáneo es mejor tolerado pero puede escocer en la zona.",
    combinesWithAvoid: "Se combina a veces con MOTS-c por su rol mitocondrial compartido; sin estudios formales de esa combinación.",
  },
  {
    name: "SS-31 (Elamipretida)",
    route: "Subcutánea",
    commonDose: "20",
    doseUnit: "mg",
    vialAmount: "50",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día",
    categories: ["longevidad"],
    tags: ["Longevidad", "Mitocondria"],
    description: "Péptido que se concentra en la mitocondria y protege su membrana interna; muy en tendencia en la comunidad de longevidad.",
    halfLife: "~2-4 horas",
    halfLifeConfidence: "medio",
    howItWorks:
      "Se acumula selectivamente en la membrana interna de la mitocondria, protegiéndola del daño oxidativo y mejorando su eficiencia energética.",
    mostReported: ["Más energía reportada", "Mejor resistencia física", "Interés en salud cardiovascular"],
    evidenceLevel:
      "Evidencia fuerte y creciente: aprobado por la FDA en 2025 (Forzinity) para el síndrome de Barth; en investigación para otras condiciones.",
    commonSideEffects: "Enrojecimiento en el punto de inyección; generalmente bien tolerado en los ensayos.",
    combinesWithAvoid: "Se combina con NAD+ en protocolos de longevidad mitocondrial. Sin interacciones graves conocidas.",
  },
  {
    name: "Humanin",
    route: "Subcutánea",
    commonDose: "200",
    doseUnit: "mcg",
    vialAmount: "2",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "3x por semana",
    categories: ["longevidad"],
    tags: ["Longevidad", "Mitocondria"],
    description: "Péptido producido dentro de la mitocondria con propiedades protectoras para el cerebro y el corazón.",
    halfLife: "Minutos a horas",
    halfLifeConfidence: "bajo",
    howItWorks: "Protege a las células del estrés y la muerte celular programada, con efecto documentado sobre todo en neuronas.",
    mostReported: ["Interés en protección neurológica", "Apoyo cardiovascular en investigación"],
    evidenceLevel: "Descubierto en 2001; evidencia mayormente preclínica, con niveles circulantes que bajan con la edad.",
    commonSideEffects: "Datos de seguridad en humanos muy limitados.",
    combinesWithAvoid: "Se investiga junto a otros péptidos mitocondriales (MOTS-c, SS-31); sin protocolos combinados estandarizados.",
  },
  {
    name: "Thymalin",
    route: "Intramuscular",
    commonDose: "10",
    doseUnit: "mg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día (en ciclos de 10 días)",
    categories: ["inmunidad"],
    tags: ["Inmunidad"],
    description: "Extracto polipeptídico del timo bovino, usado como inmunomodulador en protocolos de soporte inmune.",
    halfLife: "Minutos (extracto polipeptídico)",
    halfLifeConfidence: "bajo",
    howItWorks: "Aporta pequeños péptidos que ayudan a regular y equilibrar la respuesta del sistema inmune, similar a la Timosina Alfa-1.",
    mostReported: ["Menos infecciones reportadas", "Recuperación más rápida tras enfermedad respiratoria"],
    evidenceLevel:
      "Estudiado en Rusia durante décadas; hay datos clínicos en condiciones respiratorias graves, pero poco replicados fuera de ese país.",
    commonSideEffects: "Generalmente bien tolerado; enrojecimiento leve en el punto de inyección.",
    combinesWithAvoid: "Se usa en ciclos, no de forma continua. Se combina a veces con Timosina Alfa-1 — no sumar ambos sin espaciar dosis.",
  },
  {
    name: "Pinealon",
    route: "Sublingual",
    commonDose: "5",
    doseUnit: "mg",
    vialAmount: "-",
    vialUnit: "mg",
    bacWater: "0",
    frequency: "1x al día (en ciclos)",
    categories: ["cognicion", "longevidad"],
    tags: ["Longevidad", "Cognición"],
    description: "Tripéptido corto de la familia de bioreguladores de Khavinson, enfocado en el cerebro y la glándula pineal.",
    halfLife: "Minutos",
    halfLifeConfidence: "bajo",
    howItWorks:
      "Es tan pequeño que puede entrar al núcleo de la célula, donde se cree que ayuda a regular la expresión de ciertos genes ligados al envejecimiento cerebral.",
    mostReported: ["Claridad mental reportada", "Interés en protección neurológica a largo plazo"],
    evidenceLevel: "Estudios preclínicos del programa de bioreguladores rusos; evidencia clínica en humanos muy limitada.",
    commonSideEffects: "Sin reportes relevantes de efectos secundarios.",
    combinesWithAvoid: "Se usa en ciclos cortos, similar a Epitalon. Sin datos de interacción con otros péptidos.",
  },
  {
    name: "FOXO4-DRI",
    route: "Subcutánea",
    commonDose: "5",
    doseUnit: "mg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día (ciclos cortos)",
    categories: ["longevidad"],
    tags: ["Longevidad", "Senolítico"],
    description: "Péptido senolítico diseñado para inducir la muerte selectiva de células 'zombie' (senescentes) que se acumulan con la edad.",
    halfLife: "Sin dato confiable en humanos",
    halfLifeConfidence: "sin-dato",
    howItWorks:
      "Interrumpe una interacción proteica (FOXO4-p53) que mantiene vivas a las células senescentes, provocando que mueran de forma controlada.",
    mostReported: ["Resultados llamativos en estudios animales (piel, riñón, resistencia física)"],
    evidenceLevel:
      "Sin dato confiable en humanos — la evidencia fuerte es en ratones de laboratorio (Universidad Erasmus); no hay ensayos clínicos en personas.",
    commonSideEffects: "Sin datos de seguridad establecidos en humanos.",
    combinesWithAvoid: "Al ser experimental, no se recomienda combinarlo con otros péptidos sin supervisión médica estrecha.",
  },
  {
    name: "Cerebrolysin",
    route: "Intravenosa",
    commonDose: "5",
    doseUnit: "ml",
    vialAmount: "5",
    vialUnit: "ml",
    bacWater: "0",
    frequency: "1x al día (en ciclos)",
    categories: ["cognicion"],
    tags: ["Cognición"],
    description: "Extracto de péptidos derivado de cerebro porcino, con actividad similar a varios factores de crecimiento cerebral (BDNF, GDNF, NGF).",
    halfLife: "Sin dato confiable en humanos",
    halfLifeConfidence: "sin-dato",
    howItWorks: "Aporta fragmentos de péptidos con actividad neurotrófica, apoyando la reparación y comunicación entre neuronas.",
    mostReported: ["Mejor concentración reportada", "Uso en recuperación cognitiva tras lesión"],
    evidenceLevel:
      "Estudiado en varios ensayos clínicos controlados para ACV y traumatismo craneal, aunque revisiones Cochrane señalan que la calidad de la evidencia es limitada.",
    commonSideEffects: "Generalmente bien tolerado; requiere aplicación IV, lo que sube el riesgo de reacciones en el punto de infusión.",
    combinesWithAvoid: "Se usa en ciclos definidos, no de forma continua. No es un péptido para autoaplicación sencilla (requiere vía IV).",
  },
  {
    name: "Cortexin",
    route: "Intramuscular",
    commonDose: "10",
    doseUnit: "mg",
    vialAmount: "10",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día (en ciclos)",
    categories: ["cognicion"],
    tags: ["Cognición"],
    description: "Extracto de péptidos de corteza cerebral bovina, similar en concepto a Cerebrolysin pero de aplicación intramuscular.",
    halfLife: "Sin dato confiable en humanos",
    halfLifeConfidence: "sin-dato",
    howItWorks: "Aporta péptidos neurotróficos de bajo peso molecular que apoyan la función y protección de las neuronas.",
    mostReported: ["Uso en recuperación cognitiva", "Más práctico que Cerebrolysin al no requerir vía IV"],
    evidenceLevel: "Usado principalmente en Rusia para distintas condiciones neurológicas; evidencia clínica limitada fuera de ese contexto.",
    commonSideEffects: "Enrojecimiento en el punto de inyección; generalmente bien tolerado.",
    combinesWithAvoid: "Se usa en ciclos, no junto a Cerebrolysin (mecanismo redundante).",
  },
  {
    name: "Dihexa",
    route: "Oral (sublingual)",
    commonDose: "10",
    doseUnit: "mg",
    vialAmount: "-",
    vialUnit: "mg",
    bacWater: "0",
    frequency: "1x al día",
    categories: ["cognicion"],
    tags: ["Cognición", "Nootrópico"],
    description: "Molécula derivada de la angiotensina IV con fuertes propiedades procognitivas en estudios preclínicos.",
    halfLife: "Sin dato confiable en humanos",
    halfLifeConfidence: "sin-dato",
    howItWorks: "Activa el sistema HGF/c-Met en el cerebro, promoviendo la formación de nuevas conexiones entre neuronas (sinaptogénesis).",
    mostReported: ["Interés como nootrópico potente en foros", "Resultados llamativos en estudios animales de memoria"],
    evidenceLevel:
      "Sin dato confiable en humanos — desarrollado en la Universidad Estatal de Washington, con evidencia sólida solo en modelos animales.",
    commonSideEffects: "Datos de seguridad en humanos muy limitados.",
    combinesWithAvoid: "Al ser una molécula experimental, no se recomienda combinarla con otros nootrópicos sin supervisión médica.",
  },
  {
    name: "Ac-SDKP",
    route: "Subcutánea",
    commonDose: "1",
    doseUnit: "mg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día",
    categories: ["recuperacion"],
    tags: ["Cardiovascular"],
    description: "Tetrapéptido natural derivado de la timosina beta-4, estudiado por su efecto anti-fibrótico y protector del corazón.",
    halfLife: "~4.5 min",
    halfLifeConfidence: "medio",
    howItWorks: "Bloquea la proliferación de fibroblastos y la formación de tejido fibroso en corazón, riñón y otros órganos.",
    mostReported: ["Interés en protección cardíaca y renal", "Uso de nicho, poco reportado por la comunidad general"],
    evidenceLevel:
      "Estudiado indirectamente a través de los inhibidores de la ECA, que elevan sus niveles naturales; poca experiencia de uso directo documentada.",
    commonSideEffects: "Datos de seguridad en humanos limitados por uso directo (no es un fármaco aprobado como tal).",
    combinesWithAvoid: "Poco combinado en protocolos de la comunidad; se relaciona conceptualmente con TB-500 (mismo origen).",
  },
  {
    name: "LL-37",
    route: "Subcutánea",
    commonDose: "250",
    doseUnit: "mcg",
    vialAmount: "5",
    vialUnit: "mg",
    bacWater: "2",
    frequency: "1x al día",
    categories: ["inmunidad"],
    tags: ["Inmunidad"],
    description: "Péptido antimicrobiano natural del sistema inmune humano, con rol en la defensa contra bacterias, hongos y virus.",
    halfLife: "Variable",
    halfLifeConfidence: "sin-dato",
    howItWorks: "Ataca directamente la membrana de microorganismos y además regula la respuesta inflamatoria del sistema inmune.",
    mostReported: ["Interés en apoyo inmune general", "Uso de nicho en la comunidad de longevidad/inmunidad"],
    evidenceLevel:
      "Bien caracterizado a nivel biológico (es la única catelicidina humana conocida), pero con poca experiencia documentada de autoaplicación.",
    commonSideEffects: "Datos de seguridad en humanos por autoaplicación muy limitados.",
    combinesWithAvoid: "Su producción natural depende de la vitamina D — mantener buenos niveles de vitamina D se considera complementario.",
  },
  {
    name: "Testosterona Cipionato",
    route: "Intramuscular",
    commonDose: "100",
    doseUnit: "mg",
    vialAmount: "2000",
    vialUnit: "mg",
    bacWater: "0",
    frequency: "1x por semana",
    categories: ["libido"],
    tags: ["TRT"],
    description:
      "Éster de testosterona inyectable de acción prolongada, el más recetado en Estados Unidos para TRT (terapia de reemplazo de testosterona). Viene disuelto en aceite: no necesita agua bacteriostática.",
    halfLife: "~8 días",
    halfLifeConfidence: "alto",
    howItWorks: "Libera testosterona de forma gradual desde el tejido muscular, manteniendo niveles estables con una inyección semanal o quincenal.",
    mostReported: ["Más energía y libido", "Mejor composición corporal", "Mejor ánimo en hipogonadismo diagnosticado"],
    evidenceLevel: "Evidencia fuerte: aprobado por la FDA y usado en TRT desde hace décadas, con farmacocinética muy bien documentada.",
    commonSideEffects: "Acné, retención de líquidos, cambios de ánimo, supresión de la producción natural de testosterona (por eso se combina con HCG/Gonadorelina).",
    combinesWithAvoid: "Se combina con HCG o Gonadorelina para mantener la función testicular. No combinar con otro éster de testosterona a la vez (es redundante).",
  },
  {
    name: "Testosterona Enantato",
    route: "Intramuscular",
    commonDose: "100",
    doseUnit: "mg",
    vialAmount: "1000",
    vialUnit: "mg",
    bacWater: "0",
    frequency: "1x por semana",
    categories: ["libido"],
    tags: ["TRT"],
    description:
      "Éster de testosterona de acción prolongada, el más usado en Europa para TRT; farmacocinética casi idéntica al Cipionato. Viene disuelto en aceite: no necesita agua bacteriostática.",
    halfLife: "~4-5 días",
    halfLifeConfidence: "alto",
    howItWorks: "Libera testosterona de forma gradual desde el músculo, con una vida media algo más corta que el Cipionato.",
    mostReported: ["Más energía y libido", "Mejor composición corporal"],
    evidenceLevel: "Evidencia fuerte: aprobado por la FDA, considerado clínicamente intercambiable con el Cipionato.",
    commonSideEffects: "Acné, retención de líquidos, supresión de la producción natural de testosterona.",
    combinesWithAvoid: "Se combina con HCG o Gonadorelina para mantener la función testicular. No combinar con otro éster de testosterona a la vez.",
  },
];
